### ISSUE TITLE
Is firefox supported?

### ISSUE THREAD

**Issue by timbod7** [zalo/CascadeStudio#114]
The page opens correctly on firefox 92.0 and generally  seems to function as intended - changes in the code window are reflected in the CAD view after pressing control-s.

However the "Save Project" and "Load Project" buttons seem to have no effect in firefox. In chrome they open file dialogs as expected.

**Comment by timbod7** [comment]
Perhaps this PR caused a regression:

https://github.com/zalo/CascadeStudio/pull/39

?

**Comment by Irev-Dev** [comment]
My guess is that this would have fixed it
https://github.com/zalo/CascadeStudio/pull/113/files
