### ISSUE TITLE
Uncaught exception in Text3D on non-ascii chars

### ISSUE THREAD

**Issue by speters** [zalo/CascadeStudio#19]
Text3D gives an uncaught exception when evaluating a string containing non-ascii characters.

Reproduce at https://zalo.github.io/CascadeStudio/ with 
`Translate([-25, 0, 40], Text3D("Hi äÖ"));`

PS:
`let holeRadius = Slider("Rädiüs", 30 , 20 , 40);` prints fine on the user-interface.

**Comment by zalo** [comment]
[It looks like the default font doesn't include those characters, but `Roboto` does.](https://zalo.github.io/CascadeStudio/?code=C0mtKDF20VDyyFR4ck1JR8HYTEfBQM%2FQVEdBKSg%2FKb8kX0nTGgA%3D&gui=q1ZKzs8tyM9LzSvxS8xNVbJSSk4sTk5MSQ3LTC1X0lHyTS3OCEotVrIy0DOE84IS89KBSqMN9AwMdYxidZScE5MzUu2VrEqKSlN1lIISUzJLgVqMDWBsmAYjAx0Tg9haAA%3D%3D)
