### ISSUE TITLE
saving doesn't work for me?

### ISSUE THREAD

**Issue by m9tz** [zalo/CascadeStudio#82]
what do I have to do? I can't save anything nothing hapend when I press any save or load button. Do I have to clone the project to my account? I have install it as an app in chrome under debian/testing.

**Comment by m9tz** [comment]
moved

**Comment by boschie** [comment]
Where to?

**Comment by Irev-Dev** [comment]
@boschie https://github.com/zalo/CascadeStudio/discussions/71#discussioncomment-431719
